// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhkqf9NgNkArbbrCgcoziX-pUL6PaeJeA',
    appId: '1:870294065724:web:69544491d8cd2a0372e939',
    messagingSenderId: '870294065724',
    projectId: 'flutterapp-52b65',
    authDomain: 'flutterapp-52b65.firebaseapp.com',
    storageBucket: 'flutterapp-52b65.firebasestorage.app',
    measurementId: 'G-SC1FMYT0J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz54YYWm4ZNOMToIc6vkN0Ut1HcUV3mTQ',
    appId: '1:870294065724:android:b13c1bc203a28eb072e939',
    messagingSenderId: '870294065724',
    projectId: 'flutterapp-52b65',
    storageBucket: 'flutterapp-52b65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvtKGN9StPxciBFZ-C1lV62TsaUGijAsg',
    appId: '1:870294065724:ios:cc0cbf54c201249172e939',
    messagingSenderId: '870294065724',
    projectId: 'flutterapp-52b65',
    storageBucket: 'flutterapp-52b65.firebasestorage.app',
    iosBundleId: 'com.example.lab2211213',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvtKGN9StPxciBFZ-C1lV62TsaUGijAsg',
    appId: '1:870294065724:ios:cc0cbf54c201249172e939',
    messagingSenderId: '870294065724',
    projectId: 'flutterapp-52b65',
    storageBucket: 'flutterapp-52b65.firebasestorage.app',
    iosBundleId: 'com.example.lab2211213',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhkqf9NgNkArbbrCgcoziX-pUL6PaeJeA',
    appId: '1:870294065724:web:0fad1f26d13cabf072e939',
    messagingSenderId: '870294065724',
    projectId: 'flutterapp-52b65',
    authDomain: 'flutterapp-52b65.firebaseapp.com',
    storageBucket: 'flutterapp-52b65.firebasestorage.app',
    measurementId: 'G-WB4VQ3P8Q4',
  );
}
